### ISSUE TITLE
Spacejam: Unknown error with exit code 'null'

### ISSUE THREAD

**Issue by dpankros** [practicalmeteor/spacejam#50] opened 2016-02-12 15:15 UTC
I need some help figuring out what's going on with this.  I just installed spacejam for all users (`sudo -H npm install -g spacejam`) and tried `spacejam test-packages ./` and I get:

```
$ spacejam test-packages ./
spacejam: spawning meteor
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
spacejam: meteor mongodb is ready
spacejam: killing meteor
spacejam: Unknown error with exit code 'null'. Exiting.
```

This package works fine and all tests pass using `meteor test-packages ./` Worse, it does the same for all packages.  That makes me pretty confident it's a installation or configuration issue, but I'm sure where to look. Any ideas?  I've tried all sorts of combinations of options, like using the system phantomjs, etc, to no avail.

**Comment by rbabayoff** [comment] 2016-03-11 23:43
@dpankros I have nothing to go on here. Questions:

1. What OS r u on?
2. What version of meteor?
3. Is the package open source? Can I try it with your package?

**Comment by dpankros** [comment] 2016-03-12 00:13
OSX 10.11.3
Meteor 1.2.1
My branch of the package is at: https://github.com/dpankros/meteor-schema-index
I ran into this problem trying to figure out the issue with this pull request: https://github.com/aldeed/meteor-schema-index/pull/4

As I said previously, if I run `spacejam` on ANY package it fails (not just this one) and it's always the same error.  `mtp ./` or `meteor test-packages ./` work just fine.

For example, packages internal for my company (we have at least 10) fail on my machine if I use spacejam, but the same packages work just fine on our CI server.  (CI server is running ubuntu)  

Any other info I can provide?

**Comment by schoepke** [comment] 2016-05-03 11:23
Did you get it to work somehow?
If not, could this be related to issue #30 ?

I know that issue is about Windows but I've been having similar hickups and it could be caused by ps process handling peculiarities on OSX as well.

Have you tried running spacejam with the --loglevel debug option?
Maybe the log output help pinpointing what function or spawned process fails.

**Comment by dpankros** [comment] 2016-05-03 17:35
Nope.  It's still broken.
```
$ spacejam --loglevel trace test-packages ./
Spacejam.constructor()
CLI.constructor()
CLI.exec()
command: test-packages
CLI.exec() options: { loglevel: 'trace', packages: [ './' ] }
Spacejam.testPackages() { loglevel: 'trace', packages: [ './' ] }
{ 'phantomjs-script': 'phantomjs-test-in-console',
  'phantomjs-options': '--load-images=no --ssl-protocol=TLSv1',
  loglevel: 'trace',
  packages: [ './' ] }
Meteor.testPackages() { '0': 
   { 'phantomjs-script': 'phantomjs-test-in-console',
     'phantomjs-options': '--load-images=no --ssl-protocol=TLSv1',
     loglevel: 'trace',
     packages: [ './' ] } }
meteor options: { dir: '.',
  port: 4096,
  packages: [ './' ],
  'driver-package': 'test-in-console',
  'meteor-ready-text': '=> App running at:',
  'meteor-error-text': 'Waiting for file change.',
  'phantomjs-script': 'phantomjs-test-in-console',
  'phantomjs-options': '--load-images=no --ssl-protocol=TLSv1',
  loglevel: 'trace' }
meteor cwd=/xxxxx/xxxxxxx/xxxxxx/packages/meteor-autojoin
Meteor._globPackages() { '0': [ './' ] }
meteor args= [ 'test-packages',
  '--driver-package',
  'test-in-console',
  '--port',
  4096,
  './' ]
ChildProcess.constructor()
ChildProcess.spawn() meteor [ 'test-packages',
  '--driver-package',
  'test-in-console',
  '--port',
  4096,
  './' ]
spacejam: spawning meteor
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
MeteorMongodb.constructor() { '0': 13352 }
MeteorMongodb.findAllChildren() {}
@meteorPid 13352
spacejam: meteor mongodb is ready
ChildProcess.process.on 'exit': @command=meteor @killed=false code=1
ChildProcess.kill() signal=SIGTERM @command=meteor @killed=false
spacejam: killing meteor
MeteorMongodb.process.on 'exit': code=1
MeteorMongodb.kill() killed= false
Spacejam.onMeteorMongodbKillDone() null
spacejam: Unknown error with exit code 'null'. Exiting.

```

**Comment by rbabayoff** [comment] 2016-07-15 00:37
@dpankros can you try and reinstall meteor? Some issues have been solved this way.

**Comment by DominikGuzei** [comment] 2016-08-09 11:01
I have a similar problem … using 1.6.2-rc.4 version of spacejam:

```
{ [Error: UNKNOWN, unknown error '/private/var/folders/cz/fnf__xc15sn5lg_drgbyfl9c0000gn/T/meteor-test-run2nqy8r']
  errno: -1,
  code: 'UNKNOWN',
  path: '/private/var/folders/cz/fnf__xc15sn5lg_drgbyfl9c0000gn/T/meteor-test-run2nqy8r',
  syscall: 'readdir' }

/Users/dominik/.meteor/packages/coffeescript/.1.0.17.9a143n++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: UNKNOWN, open '/path/to/code/node_modules/webdriverio/test/site/platforms/ios/www/components/jquery-ui/themes/ui-lightness/jquery.ui.theme.css'
spacejam: meteor exited with code: 8
spacejam: killing phantomjs
spacejam: meteor is crashing server side. Exiting.
spacejam: Unknown error with exit code 'null'. Exiting.
```

**Comment by thiagodelgado111** [comment] 2016-08-11 01:25
Same here running on OSX
Meteor 1.4
Mongo 3.2.6

It seems that the process explorer package can't find mongod process 
`Found meteor mongod child with pid:  undefined`


Details:
```
Spacejam.constructor()
CLI.constructor()
CLI.exec()
command: test
CLI.exec() options: { 'driver-package': 'practicalmeteor:mocha-console-runner',
  loglevel: 'debug',
  coverage: 'out_lcovonly',
  packages: [],
  command: 'test' }
Spacejam.testPackages() { 'driver-package': 'practicalmeteor:mocha-console-runner',
  loglevel: 'debug',
  coverage: 'out_lcovonly',
  packages: [],
  command: 'test' }
{ 'phantomjs-script': 'phantomjs-test-in-console-with-coverage.js',
  'phantomjs-options': '--load-images=no --ssl-protocol=TLSv1',
  'driver-package': 'practicalmeteor:mocha-console-runner',
  loglevel: 'debug',
  coverage: 'out_lcovonly',
  packages: [],
  command: 'test' }
Meteor.runTestCommand() { '0': 'test',
  '1':
   { 'phantomjs-script': 'phantomjs-test-in-console-with-coverage.js',
     'phantomjs-options': '--load-images=no --ssl-protocol=TLSv1',
     'driver-package': 'practicalmeteor:mocha-console-runner',
     loglevel: 'debug',
     coverage: 'out_lcovonly',
     packages: [],
     command: 'test' } }
meteor options: { dir: '.',
  port: 4096,
  packages: [],
  'driver-package': 'practicalmeteor:mocha-console-runner',
  'meteor-ready-text': '=> App running at:',
  'meteor-error-text': 'Waiting for file change.',
  'phantomjs-script': 'phantomjs-test-in-console-with-coverage.js',
  'phantomjs-options': '--load-images=no --ssl-protocol=TLSv1',
  loglevel: 'debug',
  coverage: 'out_lcovonly',
  command: 'test' }
meteor cwd=/code/app
Meteor.getTestArgs() { dir: '.',
  port: 4096,
  packages: [],
  'driver-package': 'practicalmeteor:mocha-console-runner',
  'meteor-ready-text': '=> App running at:',
  'meteor-error-text': 'Waiting for file change.',
  'phantomjs-script': 'phantomjs-test-in-console-with-coverage.js',
  'phantomjs-options': '--load-images=no --ssl-protocol=TLSv1',
  loglevel: 'debug',
  coverage: 'out_lcovonly',
  command: 'test' }
meteor args= [ 'test',
  '--driver-package',
  'practicalmeteor:mocha',
  '--port',
  4096 ]
ChildProcess.constructor()
ChildProcess.spawn() meteor [ 'test',
  '--driver-package',
  'practicalmeteor:mocha',
  '--port',
  4096 ]
spacejam: spawning meteor
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
MeteorMongodb.constructor() { '0': 18009 }
MeteorMongodb.findAllChildren() {}
@meteorPid 18009
spacejam: meteor mongodb is ready
Found meteor mongod child with pid:  undefined
```

**Comment by thiagodelgado111** [comment] 2016-08-11 01:25
BTW, I've tried that package from node console manually and it couldn't find the `mongod` process either

**Comment by BenAychh** [comment] 2016-08-11 17:04
I was having the same issue on OSX (El Capitan). Installing the RC seemed to fix it for me but now spacejam never exits after running the tests. I get down to the line `(STDERR) MochaRunner.runServerTests: failures: 0` but it never exits. (It is also no longer showing the individuals results of the tests in my console.

**Comment by dpankros** [comment] 2016-08-11 20:23
@rbabayoff BTW, reinstalling meteor didn't affect the behavior in any way.

**Comment by DominikGuzei** [comment] 2016-08-23 10:59
Is there any update on this issue?  i have tried any combination of spacejam and node and practicalmeteor:mocha but the issue remains. The tests are passing correctly for me but spacejam always exists like this (no matter what the actual test results were):

```
--------------------------------------------------
---------------------RESULTS----------------------
PASSED: 33
FAILED: 0
SKIPPED: 0
TOTAL: 33
--------------------------------------------------
--------------------------------------------------

W20160823-12:58:11.205(2)? (STDERR) MochaRunner.runServerTests: failures: 0
spacejam: phantomjs exited with code: 0
spacejam: killing meteor
spacejam: Unknown error with exit code 'null'. Exiting.
```

The problem here is that the return code is always `0` which makes it unusable on a CI server

**Comment by thiagodelgado111** [comment] 2016-08-31 20:59
any update on this one?

**Comment by DominikGuzei** [comment] 2016-08-31 21:30
Yeah we still have that problem and consider switching away from spacejam because of it.

**Comment by noahadler** [comment] 2016-09-20 14:06
I'm having this problem as well (OSX, tinytest).  I'm trying to go through the code and see if I can come up with a patch, but I don't know if I will succeed.  Is there a viable alternative to spacejam someone can recommend?

**Comment by ughitsaaron** [comment] 2016-10-26 19:20
+1 for this issue. Also having this problem.

**Comment by reywood** [comment] 2017-02-01 00:35
I created a fork of this repo with the changes in the pull request created by @noahadle. I also checked in the compiled JavaScript files so that the repo can be used directly with `npm install`. You can run `meteor npm install --save-dev git+https://github.com/reywood/spacejam.git` to install it and save it in your package.json file. Then, you can use it to run tests by running `node_modules/.bin/spacejam test-packages .`.

**Closed** 2018-12-26 22:47 UTC
